Features/multiple enemies
SwapnilOutscal/Battle-Tank-Training pull request #2
Opened 2019-01-30 13:26 UTC by SwapnilOutscal

- Added Bullet damage to enemy
- Added enemy damage to player
- Added Bullet collision with environment
- Added Enemy scriptableobject

2019-01-31 06:43 UTC, mayankgrover requested changes

2019-01-31 06:43 UTC, mayankgrover commented on Assets/Scripts/Bullets/BulletModel.cs
> +        private float damage = 10f;
try not to hard code values in model classes. instead, read these from a DefaultScriptableObject

2019-01-31 06:43 UTC, mayankgrover commented on Assets/Scripts/Enemy/ScriptableObject/ScriptableObjEnemy.cs
> +        public GameObject enemyPrefab;
instead of GO use EnemyView type

2019-02-01 04:45 UTC, SwapnilOutscal commented on Assets/Scripts/Enemy/ScriptableObject/ScriptableObjEnemy.cs
> +        public GameObject enemyPrefab;
Done

2019-02-01 07:19 UTC, merged